name: Deploy to Google Cloud Run

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore:
      - '**.md'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        continue-on-error: true
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        if: steps.auth.outcome == 'success'
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Google Cloud Run
        if: steps.auth.outcome == 'success'
        run: |
          gcloud run deploy cobuild-proptech \
            --source . \
            --region me-central1 \
            --allow-unauthenticated \
            --port 8080
